### ISSUE TITLE
Make sure that email activation links work properly

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#132]
By clicking an old email for account activation, it lands on a page that says activation succesful. See if that is normal behavior. If not, fix it.

**Comment by Woseseltops** [comment]
Is not normal behavior; the email is put in the log file instead of actually sent. You need to change some settings, see https://github.com/Signbank/NGT-signbank/commit/b09fa593d391358946007e265e6ded7d4518b811

**Comment by henrinie** [comment]
We are sending emails for registered users with the activation links. I have not yet looked into this, so I don't know if the old actiovation links work or not.
Thanks for your suggestions @Woseseltops I will look at them when I have time to check this behaviour.

**Comment by henrinie** [comment]
The links don't seem to function, even though they give the default response (the success template).
I am a little hesitant to start messing with the registration feature, it seems that this is the django-registration application that has been added directly to the project.
If we want to keep the registration feature (which is not that useful because someone has to give user rights anyway -> so they could just create a new account), we might want to remove this app and add it to the environment as a 3rd party package.

**Comment by stevecassidy** [comment]
Yes, at the time I integrated this I think I needed to make some changes and so copied the whole module into the project. It would be better to remove this and rely on a more up to date registration/authentication module.

For Auslan this is used to allow members of the public to register so that they can leave feedback.  We then promote users to one of the researcher roles manually via the admin pages.

Steve


—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 26 May 2016, at 12:53 PM, Henri <notifications@github.com<mailto:notifications@github.com>> wrote:


The links don't seem to function, even though they give the default response (the success template).
I am a little hesitant to start messing with the registration feature, it seems that this is the django-registration application that has been added directly to the project.
If we want to keep the registration feature (which is not that useful because someone has to give user rights anyway -> so they could just create a new account), we might want to remove this app and add it to the environment as a 3rd party package.

**Comment by henrinie** [comment]
Thanks for the reply @stevecassidy 

We might want to gather feedback from the public at some point too of the Datasets that will be made public.

Therefore we will do as you suggested and remove the application and install the up to date version as package. But his is not a priority so it will have to wait.
It might not even be that much work, since essentially many things seem to be the same. I am not sure about the data migrations though, maybe we don't need the data stored in this app currently.
