### ISSUE TITLE
Remove delete button from Gloss page

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#137]
Glosses should only rarely need to be deleted, therefore we don't need an "easy way" to delete them. It could be done in the django admin-pages if needed.

**Comment by stevecassidy** [comment]
I would suggest that you retain it but restrict it to only 'higher' level roles (eg. publisher).  In general we shouldn't rely on the admin pages for end user tasks since they allow a bit too much power.

**Comment by henrinie** [comment]
We might want to make the delete button smaller, reducing the risk of clicking it accidently.
Generally we never want to delete glosses, except the ones we might have just created by error or something.
Signbank will have connections to ELAN, or ELAN's fields will have a connection to signbank, they will change according to the changes made to signbank. Therefore any editing of gloss names or even deletion of glosses generally should not be allowed.

**Comment by ocrasborn** [comment]
I don't follow the last conclusion, @henrinie : if changes in Signbank will propagate to ELAN (which is what already happens in part, and for the other part we're working on it), chnages to glosses are not a problem as long as researchers are aware that it may happen (so that they don't mix up different variants of the same data set with different glosses).

**Comment by henrinie** [comment]
@ocrasborn Are you directly involved with ELAN or did you mean that you are working on Signbank considering this?
My viewpoint to this is the following:
Do not trust the user. If we trust that the users are aware of what happens, we are creating, in my opinion, a huge risk.
The future of Signbank is rather uncertain, at least for our version. It could be used for a long time, annotations to ELAN could be 5 years old. No one probably remembers what were in the ELAN files 5 years ago. Therefore making changes to the glosses (the name, meaning or something similar) should not be allowed, because its results can't be predicted when we have massive amounts of data that depend on them.
Also I don't know who will be adding glosses 5 years from now, the knowledge about the causes of modifying gloss names might be lost during this time period.

This is something I would like to discuss in more detail, because we are currently thinking about the potential risks that are related to use of glosses in ELAN that are exported from Signbank.

**Comment by ocrasborn** [comment]
Yes we're directly involved, and on this very issue. We just started a github repo to keep track of ELAN issues: https://github.com/vanlummelhuizen/ASL-ELAN/issues. Will comment about the content later.

**Comment by stevecassidy** [comment]
It is certainly something to worry about as the data gets used outside of the web environment.  Deletion is currently just another edit operation. It should at least be given it’s own permission which can be added to eg. Publisher or even reserved for superuser.  We could also disallow deletion and just mark glosses as deleted in some way.

Of course, if I can edit the IDGLOSS then it doesn’t matter that I can’t delete it, so that should perhaps be protected too.

One option would be to allow deletion and gloss edits up to the point that a sign is published and then forbid any changes that would invalidate the external view of the sign.

Steve

—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 3 Mar 2016, at 10:02 PM, Henri <notifications@github.com<mailto:notifications@github.com>> wrote:


We might want to make the delete button smaller, reducing the risk of clicking it accidently.
Generally we never want to delete glosses, except the ones we might have just created by error or something.
Signbank will have connections to ELAN, or ELAN's fields will have a connection to signbank, they will change according to the changes made to signbank. Therefore any editing of gloss names or even deletion of glosses generally should not be allowed.

**Comment by henrinie** [comment]
@stevecassidy Thanks for your insight, you have some very good points about this. Obviously editing gloss name should need to be restricted too.

We have a feature that allows 'locking' of glosses. At the moment it only hides the edit button from the page, I am sure that one can easily get around this.

@ocrasborn interesting, I will keep an eye on that.
Do you happen to know what the following fields should be filled with?
`LANG_DEF="http://cdb.iso.org/lg/CDB-00130975-001"`
`LANG_ID="und"`
`LANG_LABEL="undetermined (und)"`

**Comment by ocrasborn** [comment]
I didn't check, but it would appear that these fields are the specification for the language of a field in a (External) Controlled Vocab in ELAN. See its use in http://signbank.science.ru.nl/static/ecv/cngt.ecv, where we include both the English and the Dutch Annotation ID Gloss from Signbank.

**Comment by ocrasborn** [comment]
To come back to the persistency of glosses and ELAN: ELAN doesn't have any type of version management, this is left up to the user. We have the EAF files of our corpus on an SVN server, and in a new public release of corpus annotations make explicit that the files are linked to a specific version of the ECV and that annotations have not just been added/deleted but may also have changed since the last release. Choosing a gloss and sticking to it may be desirable for sign languages that have a lexicographic tradition, so that gloss choices have been (re)evaluated again and again over a long time, but in the case of NGT, we are filling Signbank and make those evaluations there as we are annotating our corpus. The same is likely to be true for all teams: as corpus annotation progresses, new signs will be encountered and earlier decisions about lemmatisation and gloss choices may need to be revised. I would much prefer to have some sort of built-in revision history for each SB entry than to limit editors in what they can do -- see https://github.com/Signbank/NGT-signbank/issues/115. 
As for ELAN functionality, we'll be working on a more direct reading of Signbank content by ELAN in the coming year. Keeping EAF files in sync with changes to the ECV exported from SB is now done by a separate script. One of the first steps we'll take is to integrate this script into ELAN so that anyone can use it. See https://github.com/vanlummelhuizen/ASL-ELAN/issues/1.
