### ISSUE TITLE
Upgrade django to version 1.8.11

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#146]
Django received a security update today.
[https://www.djangoproject.com/weblog/2016/mar/01/security-releases/](https://www.djangoproject.com/weblog/2016/mar/01/security-releases/)
Upgrade the version to dev and production, add it in to requirements.txt too.

**Comment by ocrasborn** [comment]
@Woseseltops , should we do this too? Any downsides to updating?

**Comment by henrinie** [comment]
@ocrasborn @Woseseltops , if you are running django 1.8 or 1.9 you definitely should update.
Last time we talked about this you were running 1.6 and it doesn't receive updates any more. If you are still on 1.6 upgrading to 1.8 might need some adjustments. By upgrading to 1.7 first you might see some warnings about things that will change from 1.7 to 1.8, which might be helpful in solving them beforehand.

We are on django1.8 because it is a 'long term support' version.

**Comment by Woseseltops** [comment]
@ocrasborn, we are indeed still on 1.6, because I saw no important upsides and did see two important downsides:

Upside:
* Security updates I don't really understand

Downside: 
* Upgrading might cause an endless chain of small errors popping up at various places over the coming months, as we don't have any unit tests to check whether everything's still working after the upgrade. 
* Upgrading might break support with various dependencies.

However, the fact @henrinie managed to do it makes me want to reconsider. @henrinie , can you convince us that the upsides are worth it, or that the downsides are not that bad (or both?)

PS
If this turns into a longer discussion, we should move it to our repository, as this is about the Dutch Signbank.

**Comment by henrinie** [comment]
@Woseseltops @ocrasborn I think that you should upgrade, and here is why:
* You will get the latest security updates, 1.6 is not receiving any updates anymore.
* The more you delay upgrading the django version, the harder it will (most likely) get. 
    * If you decide to make the update later on, you probably won't update just one or two versions ahead. 
    * NGT-Signbank will probably continue to get more features, making it harder to make the update later on.
* If my memory serves me right, the update wasn't that time consuming. Just follow the warnings django gives. You can easily try it in another environment to see what errors pop up.

On the other hand, Signbank is not a super security critical application as long as no one stores any sensitive information in it, and backups are taken. Therefore security might not be the first thing to consider. In auslan they seemed to collect some information about the registered users though. Many non-free (not opensource) projects are running on older django versions, so I guess it is not a super critical thing to always keep up with the versions, even if they don't receive security updates.

Some other things to consider:
The **end of life for python 2.7 is in 2020**, it might be a good idea for every of us to try to make our versions compatible with python3 now, it should be easier than in 4 years time when our products have gotten more complicated.

**Comment by henrinie** [comment]
Bugfixes to the security fix, 1.8.11 was released. https://www.djangoproject.com/weblog/2016/mar/05/bugfix-releases/

**Comment by henrinie** [comment]
@ocrasborn & @Woseseltops Is it ok to close this issue? Are you going to move this discussion over to NGT github page?

**Comment by Woseseltops** [comment]
Yes, I will do so right now. Thanks for your arguments, you convinced me :).
