### ISSUE TITLE
Previous and next signs choices

### ISSUE THREAD

**Issue by juzza81** [Signbank/FinSL-signbank#151]
Hey again,

Henna suggested earlier that there would be added buttons as previous and next sign on a gloss information page. There can be seen an example from Auslan in:
http://www.auslan.org.au/dictionary/words/abattoir-1.html

I think it would useful to test such that action.

**Comment by ocrasborn** [comment]
If I remember well, the Auslan buttons worked to move to the previous/next 'sign number', not gloss, which in their DB is more or less the same, as most data were entered in one go.

**Comment by henrinie** [comment]
I am not so sure about this.
In what kind of use cases would the user want to go to the next gloss? The user can't know what the next gloss is (unless we show that inside the button).
And the big question still remains, **what is the next gloss?** Is it the next gloss name in alphabetical ascending order, or descending order?
Is it the next gloss in search results sorted according to gloss name ascending/descending? We show a list of search results on gloss page already, so that feature could be used for this functionality.

I tested the auslan next/previous buttons. I was on page *Keywords: washing machine*, then I did press next and it gave me: *cow, cattle, bull*, then *court*, after that *party*, then *wardrobe* and so on. For me that is not useful at all, but if someone can suggest how this would be useful, I can implement this feature.

**Comment by henrinie** [comment]
According to my understanding you want this feature to be able to scroll through the glosses in signbank in the same order as they are in your excel. If this is not right, please correct me and explain the usecase in more detail.

I will try to explain the problem I see in this.
This feature might be useful now, since you have just added the glosses to signbank and you are filling the information for each gloss. The order of the new glosses that you are editing might match your excel file right now.

But lets go forward in time, you have added more glosses, and the amount of glosses in Signbank has been tripled. Now scrolling the glosses by hitting next would not give the results you were expecting, you would have to scroll through tens or hundreds of glosses to arrive to the next 'new gloss'. This is because tens or hundreds of glosses could have been added "in between of the old glosses" (according to the alphabetical order).

A solution to this could be a search feature that allows you to search *glosses added* during a certain time period, but getting this time period just right might be quite hard. But lets proceed with the idea that you could search by time period. If this was the case, this feature is already implemented since we are showing search results on the Gloss page (gloss_detail).

We could also use tags to represent a set of added glosses. Each time we add a set of glosses, we could give that set a tag ('*Sep16glosses*' for example) and add that tag to each gloss added. There are other possibilities too, but all of this depends on the process and workflow you want to use to add glosses.

**Comment by stevecassidy** [comment]
You’d need to talk to Trevor to get the full argument but my understanding of the Auslan use of sign numbers is that it imposes a ‘dictionary order’ on signs so that you can step through them in that way.  New signs are added with a sign number that puts them in the ‘right’ position in dictionary order.

We’ve discussed this a little, I understand that the ordering is based on various phonetic properties of signs but to define the ordering that way would be less reliable, perhaps due to incomplete data for some signs.   So Trevor prefers the model of assigning a numerical ordering.

There is an issue with running out of sign numbers since the field is an integer. Trevor leaves a gap between signs by default to allow insertion of new signs. The solution to this in the longer term would be to allow floating point sign numbers.

So, that’s the perspective from Auslan as I understand it.  If you have no sense of ‘dictionary ordering’ then the next sign button doesn’t make sense. If you can define an ordering in another way (eg. alphabetic ordering on the IDGLOSS) then you could use that and generalise the next/previous gloss methods to deal with both the sign number method and the other ordering based on configuration settings.

Steve

—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 15 Mar 2016, at 12:47 AM, Henri <notifications@github.com<mailto:notifications@github.com>> wrote:


According to my understanding you want this feature to be able to scroll through the glosses in signbank in the same order as they are in your excel. If this is not right, please correct me and explain the usecase in more detail.

I will try to explain the problem I see in this.
This feature might be useful now, since you have just added the glosses to signbank and you are filling the information for each gloss. The order of the new glosses that you are editing might match your excel file right now.

But lets go forward in time, you have added more glosses, and the amount of glosses in Signbank has been tripled. Now scrolling the glosses by hitting next would not give the results you were expecting, you would have to scroll through tens or hundreds of glosses to arrive to the next 'new gloss'. This is because tens or hundreds of glosses could have been added "in between of the old glosses" (according to the alphabetical order).

A solution to this could be a search feature that allows you to search glosses added during a certain time period, but getting this time period just right might be quite hard. But lets proceed with the idea that you could search by time period. If this was the case, this feature is already implemented since we are showing search results on the Gloss page (gloss_detail).

We could also use tags to represent a set of added glosses. Each time we add a set of glosses, we could give that set a tag ('Sep16glosses' for example) and add that tag to each gloss added. There are other possibilities too, but all of this depends on the process and workflow you want to use to add glosses.
