### ISSUE TITLE
Exporting glosses to ELAN

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#153]
**This issue is for discussion considering the implementation of exporting glosses from Signbank to ELAN.**

I can think of two possible solutions for implementing this feature:
- Direct link to Signbank [we are testing this method in FinSL Signbank]
- Having a downloadable ecv (externally controlled vocabulary) file [as far as I know, NGT Signbank uses this method]

Each has its advantages and disadvantages. A combination of these two might be ideal, if it is possible to use both at the same time. I propose that we try to implement the easiest and simplest method that would require the least amount of work from anyone.
### Direct link method

This would always guarantee that the annotator would have the latest version of the dictionary when annotating. Assuming that the Signbank server is not down and the annotator has a network connection. _It might be possible to make the ECV also a downloadable file, I think it would even work right now, just open the link and save it as XML._

**Good**
- Always up to date
- No need to mess with ecv files
- No need to make sure that ELAN files are paired with the right versions of the ecv files
- Simple to use, connect the ecv to Signbank once and it updates the dictionary every time the ELAN file is loaded

**Bad**
- Does not work offline (unless the annotator opened the ELAN file when online, and did not close ELAN)
- In ELAN files glosses would change according to changes made to Signbak (hard to predict the future). Can be 'solved' by copying the annotations to another row that has no _connection_ to Signbank.
- Would be _open to public_ for anyone who knows the link, but this data would only include the gloss names and perhaps keywords/comments/something else. I don't know if it would be possible to authenticate via ELAN to make the data available only to registered Signbank users.
### Downloadable files method

We would place ECV files somewhere (on Signbank server perhaps) and users could download these links. We would save these files every day (or every day if changes to Signbank have been made), and they would be versioned according to this date.

**Good**
- You could manually keep versions, the data in ELAN files would not change when changes are made to Signbank
- Makes offline editing possible (if the annotator has downloaded the ECV file before)
- Not open to the public (people would need user rights to Signbank to download the files from Signbank)

**Bad**
- Maintaining multiple files (possibly hundreds)
- Making sure each ELAN file is paired with the correct ECV file
- It might be a bad thing that changes made to Signbank don't update to ELAN, if this behaviour would be desirable. It would mean less need to update ELAN files when changes are made (**Do you need to update old ELAN files annotations**?)
- You would not always have the most up to date dictionary from Signbank

**Comment by juzza81** [comment]
It would be good to know you others´ experiences on this field. Which of them would run better for efficient annotation and co-operation between Signbank + Elan?

**Comment by henrinie** [comment]
@ocrasborn  could you elaborate on how you do annotations in ELAN with Signbank?
Like you have said earlier you use the file based method to handle the externally controlled vocabularies. Why have you chosen this way and what problems do you see in the 'direct link' way I have described in this issue?

**Comment by ocrasborn** [comment]
A few comments (sorry for taking so long!):
* The ECV route is currently there because it was developed when we had no Signbank, and had our lexical data in an Excel file.
* I would much prefer the direct link scenario, I think, if indeed there is a cached version for offline work. This is not too much unlike the ECV scenario perhaps.
* I see mostly advantages in a workflow where changes in Signbank are propagated to the corpus. One problem that will remain though is that changes will only be propagated when a file is opened. We currently have an ELAN function in the making (presently an external script) that actually updates the whole corpus, and not just the open EAF file. One disadvantage is that the corpus changes during the course of a study. The solution to that is now also to 'freeze' the corpus, that is create a copy of a certain version (we have our EAF files on a SVN server), and I think that will often be a useful thing to do: also in the corpus itself annotations change.
* This script also addresses some other scenarios, most prominently that annotators can add annotations that are not from the vocabulary but manually typed in. This is presently very useful for two types of cases: 1) to add new glosses before adding them to Signbank (which might change if ELAN gets a function 'add this string as a new Signbank record and create an ECV link'); 2) to add glosses with modifiers such as suffix ? (doubt as to whether this gloss is correct) or prefix ~ (false start). This could theoretically also be done via a child tier, but that has too many disadvantages.

**Comment by juzza81** [comment]
Thanks Onno!
You mentioned in Slovenia that there is processing such that workflow within Elan which makes a possibility manually to add new glosses in Elan (which have not yet in a SB lexical database) and them then will be updated to SB automatically. Did I understand that right or? 

What is the worth to us now do at this current stage? Our current situation in annotation process:

1st step during summer:
- checking through all added glosses in Excel file
- transferring these glosses to SB and complete with videos + translation equivalents
- testing Signbank+Elan by interface

2nd step after summer:
- starting use only Signbank+Elan together (so we will give up Elan version 4.6.2 and change to 4.9.4 after test round)
- then new annotations with help of Signbank and using by direct link method which means that we can add new glosses straight from Elan to SB automatically (you said this development step is maybe ready till December, right?). But during fall it is still wise to add new glosses to SB manually?

Comments for our tentative work process plans?

**Comment by henrinie** [comment]
This certainly is an interesting topic.
The current workflow is not ideal, but it seems to work. If the data in the eaf-files is interesting, it would be rather inconvenient that the files are spread around on multiple individuals computers. Therefore a central place for storing them (SVN server) is a good solution, if two persons don't edit the same file at the same time.
@ocrasborn Do you store the video files on the SVN server too?

**Comment by ocrasborn** [comment]
@juzza81  : 
1) yes, we have developed a new ELAN function (currently in testing) that adds ECV links to all glosses in the corpus (well, a domain in ELAN) for which there is a match with the Annotation ID Gloss: Dutch in Signbank. It also updates the glosses that are stored in the EAF should they have been revised in ELAN. It should be released in the next ELAN version in a couple of months, but you could have a test version if you like.
2) This also relates to your workflow: yes, you can add new glosses to ELAN files and to Signbank in parallel, then run the above mentioned script, to establish the ECV link.

**Comment by ocrasborn** [comment]
@henrinie :
Nah, we don't store the movies on SVN, as they need no versioning, are rarely updated, and are big to transfer over the network. We have them on each local machine, and on a backup server and some other backup disks. (And in The Language Archive: https://hdl.handle.net/1839/00-0000-0000-0004-DF8E-6@view

**Comment by henrinie** [comment]
We have had many things change in the past.
We need to verify that the export feature is working as we want.
- make sure that the language iso-codes are utilized
- use langue archives iso links for languages that are exported

**Comment by henrinie** [comment]
We ran into a problem with so called "gestures" and other notes that the annotators want to use in ELAN at the end of the Gloss name.
A few examples of the usage:
GLOSS123@hands_up (all these have different markup, I just wrote the meaning in English)
GLOSS123@left_handed
GLOSS123@right_handed

Obviously if you use these in ELAN after the Gloss name (from ECV/Signbank), there will be no link between the annotated gloss and the Gloss in Signbank. The only way would be to have all these "gestures" stored in Signbank as Glosses, but that would be pretty repetetive.

Therefore I suggest that we make a new class for these "gestures". But before we do that we really need to dig into the meaning of these gestures, to me it seems like they are related to phonology? So we shall find out what they really are.

If these "gestures" are a thing on their own, we can create a new class for them, and then we can add these "gestures". We could then combine each gloss with all of the gestures when creating the Externally Controlled Vocabulary (ECV) for ELAN.

**Comment by ocrasborn** [comment]
What is the reason for wanting to store these in Signbank in the first place? Wouldn't it suffice to have a separate (External or in-line) Controlled Vocabulary on a dependent tier ('Gesture') for each gloss tier, in ELAN?

**Comment by henrinie** [comment]
@ocrasborn I haven't figured this out yet. I know absolutely nothing about ELAN.

The annotators want to write GLOSSNAME123@neg in ELAN for example, but they do not want to store GLOSSNAME123@neg in Signbank. When using ECV they have to do that shift+double click so that they can add that "@neg" part. When they do that, they break the link with the ECV(signbank).

Are you suggesting that the annotators add another tier (row?) for these "gestures"? I don't know what an "in-line CV" is, or what dependent tiers are.
If that is the case, then they would have quite many new tiers(rows?) for these gestures, as they are annotating left and right hand separately, while there are two people in the video, so they need 4 tiers(rows?) for this alone.

**Comment by ocrasborn** [comment]
A dependent tier (if specified for the right type, "Symbolic Association"), links annotations to other annotations, copying the exact time interval of the parent annotation (the gloss, in this case). They can be conveniently displayed along with the parent annotations in different ways. It's the only way to keep the glosses linked to the Signbank ECV, at the moment. To restrict the possible values on any tier, in this case the child tier of the gloss tier, one can create a controlled vocabulary of possible values in the ELAN file itself (it's stored in the XML along with the other annotations in that case). Alternatively, to share a CV with other files, one can include a link to an External CV (ECV) on a web server somewhere. This is what we currently do with the glosses in Signbank: export it (publish it) as a .ecv file on a web server, and include a link in each ELAN file (.eaf) to that url.

**Comment by henrinie** [comment]
We decided to use child tiers for additional information.

**Comment by juzza81** [comment]
Hey all,
@henrinie @ocrasborn @jajokera 

I want to check some issues before we will start to annotate with a new system. Henri earlier explained that the direct link method includes many advantages such as:
- always up to date
- no need to mess with ecv files
- no need make sure that ELAN files are paired with the right versions of the ecv files

Onno, your team use the downloadable files method instead of the above mentioned version. Did I understand right that you want to remain this same system because of possibility to annotate in offline, ´you currently have an ELAN function in the making (presently an external script) that actually updates the whole corpus, and not just the open EAF file´ and you have strong co-operation with ELAN developers who update its properties followed by your aims?

Alternatively, is there possible to combine the both methods? So that the annotator could choose when to use a direct link system (when online connection) or a downloadable files method (when offline connection) by simple way without extra settings on ELAN?

As you know, we have small resources here. Our current the strongest key is a Signbank base whereby we must make outlines with a long-side vision. Henri already mentioned that we decided to use child tiers by this stage. Some examples:

- Last year we annotated by this way (without ECV to Signbank)

   Gloss_1_right hand:                       BOY(handshape) WANT-NOT@neg TO-WALK  
   Gloss_1_left hand:                                                      WANT-NOT@neg@j
   Comments for gloss:
   Translation:
   Comments for translation:

Clarifications: We use a symbol @ for showing by a salient way that there is some more information about a gloss. It can be a grammatical or other categorical level. E.g.  @neg refers to a negation and @j to a freezing. This idea has been copied from Sweden. So far this solutions has worked excellently because the search functions within ELAN has been simply easy from a perspective of pedagogical, linguistic and user-friendly aims. We make currently only a basic annotation without deeply intervention in pure research study. In the future the researchers etc. can of course take advantage of our annotated data. So we want to annotate with as a bit of tiers as possible.

- This year we started officially to test annotation with ECV to Signbank. As Henri has told, there happened problems with using @ symbol. So we have solved out to start using a dependent tiers. For example:

Gloss_1_right hand:                            BOY(handshape) WANT-NOT TO-WALK
    its daugher tier:                                                          @neg
Gloss_1_left hand:                                                           WANT-NOT
    its daugher tier:                                                           @neg@j
Translation
Comments for translation:

So we can annotate to Gloss-tiers with a help of ECV connection to Signbank. Daughter tiers would be annotated only manually. We are still figuring what we should do with other sign types as gesture, depicting, numeral and fingerspelling signs. We have tentatively decided to gloss totally 5 different sign types on a Gloss tier (basic + those above mentioned 4 types) when all basic signs automatically to Signbank, but these 4 others instead of manually because e.g. it is impossible to add thousands of gestural and depictive signs to Signbank by sensible way. But it is possible that we would add some of them to Signbank if there is coming enough reliable frequency (e.g. PALM-UP).

Summary:

We annotate on a parent tier:
-basic signs (ECV to Signbank)
- depictive signs (manually)
- gestural signs (manually but same repetitive gestures automatically to Signbank)
- numeral signs (manually but same repetitive numeral signs automatically to Signbank)
- fingerspellings (manually)

+ on a child tier:
- all more informations about a sign (manually).

And we have chosen a Symbolic Association for linguistic type as you have suggested.

Onno, what do you think about our current plan? Is there someting relevant what we should still
consider and solve out?

Hopefully I was able to explain enough clearly my points and questions? Ask if some unclear.

Best regards, 
Juhana

**Comment by henrinie** [comment]
Hi @ocrasborn I would like to check one thing that I might have misunderstood.

Do you use the Controlled Vocabulary by importing a CSV-file, or are you using Externally Controlled Vocabulary with a link to a file/feed (XML)?

**Comment by ocrasborn** [comment]
The latter (in the case of glosses at least).

**Comment by henrinie** [comment]
Alright, I was under the impression that you would download the ECV as a file and then load the glosses from that file.
But it seems now that we are using the exact same method when importing the gloss list into ELAN.

**Comment by henrinie** [comment]
I guess this issue has been solved, at least there has been no discussion about this in a while. Closing.
