### ISSUE TITLE
Apply new copyright notice

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#185]
Moving FinSL-signbank specific discussion from [NGT-signbank #160](https://github.com/Signbank/NGT-signbank/issues/160) to here.

@stevecassidy @Woseseltops @ErwinKomen @ocrasborn Do you know what would be the correct way to apply a new copyright notice to FinSL-signbank?
I am still unsure on how should I apply the license on FinSL-signbank. We would like to continue using the original license, the *3-clause BSD license*.

**I think that Steve's copyright notice should be included as is,**
but how should I include the copyright notice of NGT-signbank?

@Woseseltops @stevecassidy This would be a very simple way to do this, is this totally wrong? Please suggest a better and more correct way if you know.

> Copyright (c) 2015-2016, Henri Nieminen (henri.nieminen@gmail.com)
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> 

What to put in here?

> Copyright (c) 2015, Wessel Stoop (w.stoop@let.ru.nl)
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> 
> Copyright (c) 2014, Steve Cassidy (steve.cassidy@mq.edu.au)
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by stevecassidy** [comment]
HI Henri,
  I would have thought that we could just extend the list of people after the copyright statement - I don’t think it needs to be just one person. The license refers to ‘copyright holders’ (plural) in at east one place.

Steve


—
Department of Computing, Macquarie University
http://web.science.mq.edu.au/~cassidy

On 4 Aug 2016, at 9:01 PM, Henri <notifications@github.com<mailto:notifications@github.com>> wrote:


Moving FinSL-signbank specific discussion from NGT-signbank #160<https://github.com/Signbank/NGT-signbank/issues/160> to here.

@stevecassidy<https://github.com/stevecassidy> @Woseseltops<https://github.com/Woseseltops> @ErwinKomen<https://github.com/ErwinKomen> @ocrasborn<https://github.com/ocrasborn> Do you know what would be the correct way to apply a new copyright notice to FinSL-signbank?
I am still unsure on how should I apply the license on FinSL-signbank. We would like to continue using the original license, the 3-clause BSD license.

I think that Steve's copyright notice should be included as is,
but how should I include the copyright notice of NGT-signbank?

@Woseseltops<https://github.com/Woseseltops> @stevecassidy<https://github.com/stevecassidy> This would be a very simple way to do this, is this totally wrong? Please suggest a better and more correct way if you know.

Copyright (c) 2015-2016, Henri Nieminen (henri.nieminen@gmail.com<mailto:henri.nieminen@gmail.com>)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

  1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

  2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

  3.  Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

What to in put here?

Copyright (c) 2015, Wessel Stoop (w.stoop@let.ru.nl<mailto:w.stoop@let.ru.nl>)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

  1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

  2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

  3.  Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Copyright (c) 2014, Steve Cassidy (steve.cassidy@mq.edu.au<mailto:steve.cassidy@mq.edu.au>)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

  1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

  2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

  3.  Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by henrinie** [comment]
Thanks for the answer @stevecassidy, that is probably a much better way to do it since the license is not going to be changed.

@Woseseltops @ocrasborn Are you going to keep your work under the same license, or are you going to switch to another one that is compatible with the 3-clause BSD license?

**Comment by henrinie** [comment]
@ocrasborn @Woseseltops 
What are you going to do with the license?
Whose names (of your team) shall I put in our copyright notice? Probably wessel, have there been any other developers before we branched from NGT?
We would like to move forward with this issue.

**Comment by Woseseltops** [comment]
Sorry for not responding, @henrinie , I completely forgot about this. 

Let me summarize my thoughts about this in a few points:
* I was paid to do this development work with university money, so I think my university holds the copyright. Maybe it would be better to put 'Radboud University' instead of the names of @erwinkomen, @ocrasborn and me.
* We have not made any license related decisions; it seems to have a low priority for now, I'll ask @ocrasborn to form an opinion quickly. 
* In other RU software projects, the vision always is to make everything as open as possible; it was paid for by public money, so the results should be given back to the public. This seems to be what is meant with "THIS SOFTWARE IS PROVIDED [...] AS IS" in the license you propose, so it might be appropriate for us to use as well. On the other hand, 'All rights reserved' seems to imply the opposite.

**Comment by ocrasborn** [comment]
* @Woseseltops : I think it would be good to settle this, as Signbank is slowly becoming more visible to others.
* I agree with @Woseseltops that it'd be better to mention Radboud University as the copyright holder in any legalese, as that's how it formally is. We can find other places (including an informal notice here or there) that identifies the developers, but also the linguists, as creators.

**Comment by henrinie** [comment]
> ... it'd be better to mention Radboud University as the copyright holder in any legalese, as that's how it formally is.

That is a valid point, in our case it should probably also be our university. I think I got a little confused here since some licenses mention the author and the organisation separately.
We can probably add a separate file for the authors part.

@ocrasborn I will edit our license so that I add Radboud University as a copyright holder. I will use the year 2015 in it (since we forked from you in 2015), is that okay?

So we will have Steve Cassidy, Radboud University (is this the official written form?) and University of Jyväskylä.
@ocrasborn @stevecassidy @Woseseltops Do everyone agree with that?

**Comment by stevecassidy** [comment]
Since you are substituting institutions here it might be better to put Macquarie University rather than my name since that's where the funds came from, it also acknowledges Trevor's input.

Steve

**Comment by henrinie** [comment]
@stevecassidy I can change your name to Macquarie University, would you still like to have your email address in there?

I also added an AUTHORS file:
https://github.com/Signbank/FinSL-signbank/blob/master/AUTHORS
@stevecassidy @ocrasborn I can add people in there if you give me names and their role during the development before we forked NGT-signbank. I am open to suggestions concerning the AUTHORS file.

**Comment by stevecassidy** [comment]
Happy to have my email address just in the AUTHORS file.

**Comment by henrinie** [comment]
The license has been updated. Therefore closing this issue.
