### ISSUE TITLE
Replace singnbank.Pages app with djangos flatpages

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#206]
I think this is a similar case to the signbank.registration - the source code is copied from django.
We could possibly delete this (partly) outdated code, and replace it with the internal flatpages.
https://docs.djangoproject.com/en/1.10/ref/contrib/flatpages/

**Comment by henrinie** [comment]
There are two possible issues: need to figure out how to integrate django-modeltranslation with flatpages, and also django-summernote editor. Although now we could look into other editors as well, I dislike the way summernote(?) generates html.

**Comment by henrinie** [comment]
It seems that other wysiwyg editors are either not easily support django-modeltranslation, have way too many features, or are not actively maintained.
I think we will still stick to django_summernote. Ckeditor seemed nice and produced better html than summernote, but integrating it with dynamic model translations didn't seem very straightforward.

**Comment by stevecassidy** [comment]
Hi Henri,
 Just to give you some background on the Pages app. It was added because the Auslan Signbank wanted to have pages with embedded video (signed) translations.   So Pages is more or less just Flatpages with the option of adding a video.   In practice, I think we only ever had one video so this wasn’t used.

I’d suggest replacing this with either flatpages or a more complete CMS solution, depending on how complex the requirements are for content pages on the site.  Flatpages is fine for just a few pages but if you want more structure (as we have on Auslan Signbank) then a CMS component would be more useful.

Steve

**Comment by henrinie** [comment]
Hello Steve,
Thank you for your insight and your suggestions.

I configured the pagevideo feature to work once, but users still seemed to prefer to upload a video to youtube. For us it has not been used so far, so it doesn't seem to be a very important feature.

We don't seem to need very many content pages, at the moment we only have the homepage and about page. For that, just like you suggested, a CMS is a bit too heavy. I've already taken the steps to replace Pages app in development with flatpages. It seems to work just fine with django-summernote and django-modeltranslation without much hassle. One thing that seems to be missing from it is the subtree menu functionality you have built into Pages app. For the few content pages we have, it is not really required though, at least not at the moment.

**Comment by henrinie** [comment]
Moved the changes into the master branch. Closing issue.
