### ISSUE TITLE
Confirmation state for Gloss

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#215]
We would like to make it possible to set a confirmation state for a gloss (confirmed or unconfirmed). These different states should be recognizable in the search listing (different colors for example), and it should also be possible to search/filter based on the states, if gloss has/doesn't have a video, or if it is locked.
The potential list of different state combinations would be: Unconfirmed, Unconfirmed with Video, Confirmed, Confirmed with Video, and Locked.

This requirement arises from the needs in annotation. It would be useful to be able to add gloss 'suggestions' to Signbank, so that they could be used when annotating with Signbanks controlled vocabulary. When a gloss is added during annotation, a video of it should be added to the gloss page immediately, making it possible for other annotators to use this unconfirmed gloss. **#212 is required for this.** If the Gloss(name) would need to be changed later on, by changing its name in Signbank would also update the ELAN files (once they are opened with Signbanks externally controlled vocabulary).

**Comment by ocrasborn** [comment]
We use tags for these kind of workflow issues. See screenshot.

![screenshot 2017-01-31 13 14 31](https://cloud.githubusercontent.com/assets/10242207/22464467/423f8620-e7b7-11e6-88ea-27af606c23b5.png)

**Comment by henrinie** [comment]
That is one option, we could then do the filtering/search by tag(s).
But at first thought it feels that it needs much more work maintaining multiple tags (adding and deleting them for each gloss), than it might take to just tick one box "confirmed/unconfirmed".

**Comment by ocrasborn** [comment]
Agree with the latter point, but that's a more general issue related to the use of pull-down menus in Signbank. There are many places where I'd much prefer to see lists of options with checkboxes when selecting (editing single signs, composing queries).

**Comment by henrinie** [comment]
I think that we will implement this feature as a yes/no choice (boolean). And we will use a checkbox for it in the search page, just as we currently use for video/no-video etc.

I think that the tags will be more useful when indicating what needs to be done to the gloss in order to make it confirmed or locked.

**Comment by juzza81** [comment]
Yeah, it would be relevant for us annotators to get an option for the unconfirmed or confirmed gloss so that we could add efficiently new glosses on Signbank and consider them there. We are now still in child´s shoes and we don´t need yet more exact categories by those grammatical levels as Onno showed via screenshot.

At this moment our the most important demands as Henri already mentioned:

- unconfirmed gloss
- unconfirmed gloss with video
- confirmed gloss
- confirmed gloss with video
- confirmed gloss with video and other properties after which the gloss page can be locked


Onno, what like experiences your team had in beginning times of Signbank? Did you use immediately same base compared to your given screenshot?

**Comment by ocrasborn** [comment]
No no, the tag list expanded as our workflow got more and more refined.

**Comment by henrinie** [comment]
Looks like we will not be implementing this, as tags have been sufficient so far for this usage.
