### ISSUE TITLE
Handshape search?

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#220]
This was a proposal. Do we need or want a feature where you could search handshapes?

**Comment by juzza81** [comment]
I and Jarkko wanna elaborate this topic:

Our point was that our team needs an efficient search function for the parameters of a sign such as:
handshape, movement, placement and orientation by this moment (in future will be needed maybe non-manual elements as fifth parameter property).

This features help us to annotate and study differents signs more exactly. Additionally, it would be useful to search signs by choosing certain parameters instead of only using written word.

**Comment by henrinie** [comment]
So do we need the phonology features? At the moment we have the following fields we could use:

`Handedness, Strong Hand, Weak Hand, Handshape Change, Relation Between Articulators, Location, Absolute Orientation: Palm, Absolute Orientation: Fingers, Relative Orientation: Movement, Relative Orientation: Location, Orientation Change, Contact Type, Movement Shape, Movement Direction, Movement Manner, Repeated Movement, Alternating Movement, Phonology Other, Mouth Gesture, Mouthing, Phonetic Variation`

Could we use some of these to store the data you need?
I **will** get rid of all these fields if we don't need them. I want to make the codebase as clear as possible when we release finsl-signbanks first version in June.

**Comment by juzza81** [comment]
This is good question which must be solved out by the whole team. I suggest that let´s talk about this in our next ´big-meeting´. I mark now that up an agenda.

**Comment by henrinie** [comment]
Not relevant currently.
