### ISSUE TITLE
Grouping translation equivalents

### ISSUE THREAD

**Issue by henrinie** [Signbank/FinSL-signbank#233]
Users would like to be able to have control over how translation equivalents fields are shown.
One of the requirements is that users would be able to group translations similarly to this:
"1. carrot, potato; 2. cucumber"

These groups and their numbers are there to represent the significance of the translations to the gloss.
We would still like to store the relations between keywords,translations and glosses.

**Comment by henrinie** [comment]
Possible solution I have been thinking of:
- Create some rules on what can be written into the translation equivalent fields, and how they can be written. Currently following the example of "1. carrot, potato; 2. cucumber".
- Create a new class to store the string representation of the translation equivalents (as they are written into the translation equivalent field).
- Parse the keywords out of the provided string when updating translation equivalents

**Comment by ocrasborn** [comment]
Isn't there also a field 'sense(s)' for this purpose, distinguishing different meanings of signs and linking them to example sentences? I think the Auslan DB uses this. @stevecassidy ?

**Comment by henrinie** [comment]
If it was in, I have removed it from FinSL-signbank.
This is just a way of listing the translation equivalents, not an example sentence.

**Comment by ocrasborn** [comment]
I understand it's different, but it's related: 1. and 2. in your example could each have a different sentence example (in a spoken language, or in a sign language).

**Comment by henrinie** [comment]
Okay well, no one has brought up anything like that before, so I don't really know.
Would example sentences be important in this kind of thing?
@juzza81 @jajokera Could you comment on this?

**Comment by juzza81** [comment]
I check that did you meant, Onno, that there would have a field in which
around a same-formed sign has been put different example sentences which help
to distinguish different meanings of the sign? Where do these sentences locate on Signbank? Own field on a gloss page or?

**Comment by henrinie** [comment]
There is some confusion about what you meant with your comments @ocrasborn 
Anyway, we are not going to implement example sentences. We do not need to link meanings to sentences.
This probably looks dictionarish, but our aim doesn't seem to be to make a dictionary. The numbering is supposed to distinguish different meaning groups for translation equivalents. That is just to show them on the gloss page, we will not save these groups or their relations.
We have multiple datasets on FinSL-signbank's production server, only one of the Datasets is probably going to use this way of writing the translation equivalents.

I am still unsure what 'sense' is?

**Comment by ocrasborn** [comment]
I'm not sure either what 'sense' is in the database, but my guess was that it is somehow linked to the different meanings that I see in the Auslan interface, see the screen shot below. Perhaps @stevecassidy can help out.
![screenshot 2017-03-14 16 07 20](https://cloud.githubusercontent.com/assets/10242207/23907134/722f775c-08d0-11e7-81d4-54fc76d3dd21.png)

**Comment by henrinie** [comment]
Interesting, thanks for pointing this out @ocrasborn !

**Comment by stevecassidy** [comment]
Hi all,
  sense in Auslan is a bit of an awkward way to record different senses for the same sign.  Any sign with a sense > 1 will look for another sign that is related as a ‘homophone’ with sense=1 and use the video associated with that sign.   See the ‘homophones’ method on the Gloss class.

Of course, a better model would have a more explicit representation of senses (meanings) than we have in Signbank.  I’ve looked at the Lemon lexical model for this which separates the lexical entry, surface form and sense as separate entities.   We did a bit of an experiment with it a few years ago but there were still too many questions relating to sign linguistics that were unanswered, so that was put on the back burner.

As I understand your original question, you want to group the translations together as they relate to different senses of the sign: "1. carrot, potato; 2. cucumber”.   So, the translations are associated with different meanings (senses) of the lexical entry (sign).  At the moment, different meanings are represented as definitions. This is well illustrated in Otto’s screenshot where we have “English = page” at the end of the Noun definitions and “English  = skim, flick through, browse” on the Verb.   Maybe it makes more sense to associate the translation with one of the definitions rather than with the Gloss itself?

That would be a big change and for Auslan at least, hard to move the existing translations and find which definitions to associate them with.

Steve


On 15 Mar 2017, 3:25 AM +1100, Henri <notifications@github.com>, wrote:

Interesting, thanks for pointing this out @ocrasborn<https://github.com/ocrasborn> !

**Comment by henrinie** [comment]
@stevecassidy Thank you for your explanation, you made a lot of things more clear to us.

> As I understand your original question, you want to group the translations together as they relate to different senses of the sign: "1. carrot, potato; 2. cucumber”. So, the translations are associated with different meanings (senses) of the lexical entry (sign).

We are not _actually_ grouping anything. It was requested that the translation equivalents could be written like that. They are still saved like they used to be: Removing number(s)+dot, splitting the values by comma or semicolon, saving translations+keywords.

We have no intention to start working on this any further. Perhaps in the distant future.

**Comment by juzza81** [comment]
Thanks for good explanations and comments! Yeah we have no intention to start defining signs to different classes in a consequence of lack of resources by this moment. But we are starting to add different translation equivalents around the gloss sign and use different punctuation marks as Henri already presented.

**Comment by henrinie** [comment]
Closing this issue since it is not relevant at the moment. It is possible to add grouped translation equivalents; those groups are just for visualization and not implemented on database level.
